### PR TITLE
Add description of repository to README

### PR DESCRIPTION
**Pull request by mdrum**
## Summary
I believe that the README should briefly describe where to find key files within a repository, for users that might not be familiar with GitHub or the traditional code file structure. This pull request is a first attempt at documenting that.

### CODE REVIEW

**Comment by jordanpadams** [comment]
@mdrum I'm not sure how we should go about merging this?

My recollection from the DMSP is the average user should not have to worry about navigating GitHub. The README should lead off with linking to the documentation and things that are more user focused.

This information seems more useful to the steward, not the user.

Can we move this information down a ways in the README, or even move it to the `src/README.md`, which is more intended for the steward?

**Comment by mdrum** [comment]
Definitely open to discussion on this. The README will only ever be adjacent to the files in the repo, but if we intend to only ever use it by linking to the file itself, then I'd be fine moving this information elsewhere.

As we currently use these repos, however, I think something like this is needed. I very much doubt anyone without programmer experience would ever imagine to look in the "src" directory for anything, and that happens to be where the most important file is.

**Comment by acraugh** [comment]
@mdrum and @jordanpadams, I think maybe the statement "The average user should not have to worry about navigating GitHub" is being taken too literally. Or maybe it's more accurate to say there are some qualifications needed.

I would say, "The average _label designer_ user should not have to worry about navigating GitHub." That is, someone trying to use a namespace to design and validate labels should not have to deal with GitHub to get to the schemas and documentation needed to accomplish that task. In my mind, a user like that lands in GitHub by clicking a link that looked promising but probably wasn't intended for them. So the top-level repo README should explain to them gently where they are, and set them back on the path they should be on: reading the User Guide; to "Latest Release" to collect their schemas; etc. These users don't want to see how it's made, thy just want the sausage, please - and preferably pre-cooked.

The average _programmer_ user probably landed in GitHub intentionally because they wanted to see the nuts & bolts. They're perfectly comfortable navigating directories (provided those directories are not mysteriously named), and since all the ldd-* repos are structured the same way I don't see a lot of point in making stewards write the same description over and over again for people who are unlikely to ever read it.  I also don't see much point in putting that description in front of the first sort of user, who is likely to start panicking about how much documentation they're going to have to read before they can find what they want and do something with it.

I would hope that the average human _end_ user - someone who is browsing labels and wants to know what an attribute means - would never end up in GitHub looking for that information in the first place. I _am_ concerned that that person might not have a ready source for that sort of information. If such a thing exists (an all-namespace attribute/class lookup database, e.g.), then it might well be worth including a pointer to that in the repo README. 

I've taken a stab at a new Display Namespace readme in the "dmsp-test" branch of that repo, if you want to eyeball something in more of a real-world state. I need to let it rest for a day or two before thinking about it again.

**Comment by acraugh** [comment]
Oh, and as a related aside, @mdrum and @jordanpadams, note that in the Display namespace readme, the link that is supposed to take you directly to the "Display" section of the https://pds.nasa.gov/datastandards/dictionaries/index-1.17.0.0.shtml page _does not do that._  It takes you to the top of the page. In order for the "#disp" to work, there has to be a file name in the URL, which in turn means you'd have to update the README for every release because the index page you get redirected to has the IM release number in the file name. So it was a nice thought, but the implementation is problematic.

**Comment by wkiri** [comment]
> Oh, and as a related aside, @mdrum and @jordanpadams, note that in the Display namespace readme, the link that is supposed to take you directly to the "Display" section of the https://pds.nasa.gov/datastandards/dictionaries/index-1.17.0.0.shtml page _does not do that._ It takes you to the top of the page. In order for the "#disp" to work, there has to be a file name in the URL, which in turn means you'd have to update the README for every release because the index page you get redirected to has the IM release number in the file name. So it was a nice thought, but the implementation is problematic.

This is also noted here: https://github.com/pds-data-dictionaries/PDS-Data-Dictionaries.github.io/discussions/12#discussion-3986207 (point 2).  One solution would be to have `index.shtml` as a symbolic link to the current release (such as `index-1.17.0.0.shtml`) and then `index.shtml#disp` could be used unchanged in the namespace `README.md`; it would be automatically followed to `index-1.17.0.0.shtml#disp`.

**Comment by acraugh** [comment]
Seems like this something we may want to do for different parts of the pds.nasa.gov site, at least until the overall redesign happens. If there is a convention (like using an alias like "current" or "latest" and just redirecting it) used by pds.nasa.gov then just extending that would be fine. 

Ultimately the whole schema distribution scheme is probably up for revamping now that the builds and releases are getting to be better coordinated with the IM build schedule. I'd like to hear stories from label designers about their various workflows before that happens.

**Comment by jordanpadams** [comment]
@wkiri @acraugh we can definitely support a "current" page to make this easier e.g. https://pds.nasa.gov/datastandards/dictionaries/index.shtml#disp would go to https://pds.nasa.gov/datastandards/dictionaries/index-1.17.0.0.shtml#disp . does not seem agreeable to you all? We will need to update our deployment for next build to have this new page supported.

**Comment by acraugh** [comment]
Seems like that would work, @jordanpadams, but I think I'm remembering that questions have been raised about what the content of this README should be in the first place, so it might end up being a moot point near-term. Still, it seems like a useful generic pointer to have available for referencing in other documentation even if not here.

**Comment by wkiri** [comment]
Sounds great, @jordanpadams !

**Comment by mdrum** [comment]
I've lost track of where this conversation went. How are we feeling about this actual pull request?

**Comment by jordanpadams** [comment]
@mdrum can we move that section down below documentation? I feel like this is power user / steward information that a general user shouldn't care about.

**Comment by mdrum** [comment]
> @mdrum can we move that section down below documentation? I feel like this is power user / steward information that a general user shouldn't care about.

This change has been made

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
